stages:
  data-ingestion:
    cmd: python .\src\data\data-ingestion.py
    deps:
    - .\src\data\data-ingestion.py
    outs:
    - .\data\raw\test.csv
    - .\data\raw\train.csv
  data-preprocessing:
    cmd: python .\src\data\data-processing.py
    deps:
    - .\data\raw\test.csv
    - .\data\raw\train.csv
    - .\src\data\data-processing.py
    outs:
    - .\data\processed\test.csv
    - .\data\processed\train.csv
  feature-engg:
    cmd: python .\src\features\features-engg.py
    deps:
    - .\data\processed\test.csv
    - .\data\processed\train.csv
    - .\src\features\features-engg.py
    outs:
    - .\data\interim\test_bow.csv
    - .\data\interim\train_bow.csv
  modelling:
    cmd: python .\src\models\modelling.py
    deps:
    - .\data\interim\train_bow.csv
    - .\src\models\modelling.py
    outs:
    - models\random_forest_model.pkl
  model-evaluation:
    cmd: python .\src\models\model-evaluate.py
    deps:
    - .\data\interim\test_bow.csv
    - .\src\models\model-evaluate.py
    - models\random_forest_model.pkl
    outs:
    - .\reports\eval_metrics.json
